- name: Assure galaxyFS dir exists
  file: path={{ galaxyFS_base_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
  become_user: root

- name: Assure indicesFS dir exists
  file: path={{ indicesFS_base_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
  become_user: root

- name: Create shed tools dir
  file: state=directory path={{ galaxy_shed_tools_dir }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

- name: Create database dir
  file: path={{ galaxy_db_dir }} state=directory owner=postgres group=postgres
  become_user: root
